#!/bin/bash
read -p "Press the flash button and press any key to upload MicroPython"
esptool.py --chip esp32 --port /dev/ttyUSB0 --baud 460800 write_flash -z 0x1000 esp32-idf3-20200612-unstable-v1.12-526-g05e5d411b.bin
